var src,node,views;$(".modal-show").click(function(){src="https://www.youtube.com/embed/"+$(this).prevAll('.samImg').attr('data-uid');node=$(this).parent().next('.video-txt-div').children('p').html();views=$(this).parent().next('.video-txt-div').children('.viewDiv').children('.views').html();$("#video-modal").modal('show');})
$("#video-modal").on('show.bs.modal',function(e){var target=$('#video-modal').children('.modal-dialog').children('.modal-content').children('.modal-body')
target.children('iframe').attr('src',src);target.children('.modal-bottom').children('.video-msg-div').children('.video-msg').empty().append(node)
target.children('.modal-bottom').children('.video-msg-div').children('.viewDiv').children('.views').empty().append(views)});$("#video-modal").on('hidden.bs.modal',function(e){var target=$('#video-modal').children('.modal-dialog').children('.modal-content').children('.modal-body')
target.children('iframe').attr('src','');target.children('.modal-bottom').children('.video-msg-div').children('.video-msg').empty();target.children('.modal-bottom').children('.video-msg-div').children('.viewDiv').children('.views').empty();});window.onload=function(){var mySwiper=new Swiper('.selectrow.swiper',{autoplay:0,loop:false,slidesPerView:'auto',spaceBetween:5,})
if(/Android|webOS|iPhone|iPod|BlackBerry/i.test(navigator.userAgent)){const selectrow=document.querySelector(".selectrow");const selectrowOffsetTop=selectrow.offsetTop;window.onscroll=function(){const scrollHeight=document.body.scrollTop||document.documentElement.scrollTop;if(scrollHeight>selectrowOffsetTop-40){selectrow.classList.add('selectrow-fixed');}else{selectrow.classList.remove('selectrow-fixed');}};}}
function sectionSwitch(num){document.querySelectorAll('.selectrow-button.active').forEach(function(element,index){element.classList.remove('active');});document.getElementById("btn"+num).classList.add('active');document.querySelectorAll('section.show').forEach(function(element,index){element.classList.remove('show');});document.getElementById("section"+num).classList.add('show');}
function sortNew(no){var ul=document.getElementById('section'+no);var lis=ul.getElementsByClassName('video-item');var ux=[];for(var i=0;i<lis.length;i++){var tmp={};tmp.dom=lis[i];tmp.date=new Date(lis[i].children[0].value);ux.push(tmp);}
ux.sort(function(a,b){return(b.date-a.date)});for(var i=0;i<ux.length;i++){ul.children[1].children[0].appendChild(ux[i].dom);}
document.getElementById("sortNewBtn"+no).classList.add("active");document.getElementById("sortViewBtn"+no).classList.remove("active");}
function sortView(no){var ul=document.getElementById('section'+no);var lis=ul.getElementsByClassName('video-item');var ux=[];for(var i=0;i<lis.length;i++){var tmp={};tmp.dom=lis[i];tmp.view=parseInt(lis[i].children[2].children[1].children[1].innerHTML.replace(/\,/g,""));ux.push(tmp);}
ux.sort(function(a,b){return(b.view-a.view)});for(var i=0;i<ux.length;i++){ul.children[1].children[0].appendChild(ux[i].dom);}
document.getElementById("sortViewBtn"+no).classList.add("active");document.getElementById("sortNewBtn"+no).classList.remove("active");}